name: vkusnoitochka_api
description: API for receiving data from Vkusnoitochka. The library has a class with static methods for retrieving data.
version: 1.0.1
repository: https://github.com/Iv2005an/vkusnoitochka_api

environment:
  sdk: ^3.3.4

dependencies:
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
